name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'  # 添加这一行
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "FLUTTER_HOME=$(pwd)/flutter" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/flutter/bin" >> $GITHUB_ENV
          echo "flutter.sdk=$(pwd)/flutter" > .local.properties
          echo $PATH  # 添加这一行，用于调试
          flutter pub get  # 添加这一行
          flutter doctor  # 添加这一行，用于验证 Flutter 是否可以正常运行

          
      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >>$GITHUB_OUTPUT
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

      - name: Build the app
        working-directory: ./project/android/
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew build --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./project/build/outputs/apk/**/*.apk
